export default{
    recommendTabs:[{
        name:"音单",
        url:"/musicList"
    },{
        name:"推荐",
        url:"/recommend"
    },{
        name:"分类",
        url:"/sort"
    }],
    searchTab:[{
        name:"综合",
        url:"sound",
        total:0
    },{
        name:"剧集",
        url:"drama",
        total:0
    },{
        name:"直播",
        url:"live",
        total:0
    },{
        name:"音单",
        url:"album",
        total:0
    },{
        name:"UP 主",
        url:"user",
        total:0
    }],
    soundTab:[{
        name:"全部",
        url:"introduction"
    },{
        name:"评论",
        url:"discuss"
    },{
        name:"图片",
        url:"images"
    }],
    channelsTab:[{
        name:"全部",
        url:"all"
    },{
        name:"M音",
        url:"Min"
    },{
        name:"铃声",
        url:"ring"
    }],
    channelMenu:[{
        name:"动态",
        url:"sounds"
    },{
        name:"评论",
        url:"comments"
    },{
        name:"成员",
        url:"admin"
    }],

}